### ISSUE TITLE
Uncaught TypeError : o.a.createRef is not a function

### ISSUE THREAD

**Issue by KunalBurangi** [nhn/toast-ui.react-image-editor#14]
## Version
    "@toast-ui/react-image-editor": "^1.0.1",

## Test Environment
Chrome , firefox , etc

## Current Behavior

I installed the package and tried to run it but it is giving me error
Uncaught TypeError : o.a.createRef is not a function
my react version is 15.5.4
```js
// Write example code
```

**Comment by jinwoo-kim-nhn** [comment]
I'm sorry for the late answer, first try version 1.2.0 and test it. 
There is an example running through `npm run storybook`.
The example works fine, so probably not a problem.

**Comment by Ats1999** [comment]
I also have the same problem.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-28T10:04:55
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-image-editor] Uncaught TypeError : o.a.createRef is not a function (#14)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by Ats1999** [comment]
> Dooray! 메일 발송 실패 안내 메일 발송 실패 안내 박시우(viewrain@nhn.com) 님께 보낸 메일이 전송되지 못하였습니다. 실패 사유를 확인해보세요. * 받는 사람 :  박시우(viewrain@nhn.com) * 발송 시간 :  2020-07-28T10:04:55 * 메일 제목 :  Re: [nhn/toast-ui.react-image-editor] Uncaught TypeError : o.a.createRef is not a function (#14) * 실패 사유 :  받는 사람이 회원님의 메일을 수신차단 하였습니다. 이 메일은 발신전용으로 회신되지 않습니다. 더 궁금하신 사항은 dooray@nhn.com 으로 문의해 주시기 바랍니다. © Dooray!.

could you write in english?

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-28T10:11:55
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-image-editor] Uncaught TypeError : o.a.createRef is not a function (#14)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by KunalBurangi** [comment]
Thanks for the rply. it got solved

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2021-02-09T16:06:30
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-image-editor] Uncaught TypeError : o.a.createRef is not a function (#14)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2021-02-09T16:07:30
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-image-editor] Uncaught TypeError : o.a.createRef is not a function (#14)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
