### ISSUE TITLE
Change image while keeping the filters/texts/objects/etc

### ISSUE THREAD

**Issue by Jaberish** [nhn/toast-ui.react-image-editor#36]
How do I change the background image used while retaining the user edits (drawings/effects/texts/etc)?
Using `loadImageFromURL` and `loadImageFromFile` clears the user edits which I do not want.
And updating the props on the < ImageEditor/> like `loadImage.path` does not seem to do anything after the initial render.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-12-03T09:58:05
          
          
            * 메일 제목 : 
[nhn/toast-ui.react-image-editor] Change image while keeping the filters/texts/objects/etc (#36)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by Jaberish** [comment]
Looks like it isn't currently supported: https://github.com/nhn/tui.image-editor/issues/195

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-12-03T14:19:06
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-image-editor] Change image while keeping the filters/texts/objects/etc (#36)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-12-03T14:20:05
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-image-editor] Change image while keeping the filters/texts/objects/etc (#36)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
